name: Thanks

on:
  issues:
    types: [opened]

  workflow_dispatch:

jobs:
    thanks:
        name: Thanks for opening an issue
        runs-on: ubuntu-latest
        permissions:
          issues: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
        - uses: actions/github-script@v9
          id: issue_comment
          with:
            script: |
                var issue_number = context.issue.number || 3;
                var repo = context.repo.repo;
                var owner = context.repo.owner;

                console.log(`issue_number: ${issue_number}`);
                console.log(`owner: ${owner}`);
                console.log(`repo: ${repo}`);

                const issue = await github.rest.issues.get({
                    repo, owner, issue_number
                });
                console.log(`issue: ${JSON.stringify(issue)}`);

                var comment = await github.rest.issues.createComment({
                issue_number: issue_number,
                owner: owner,
                repo: repo,
                body: `👋 Thanks for opening issue #${issue_number}!`
                });

                github.rest.issues.addLabels({
                issue_number: issue_number,
                owner: owner,
                repo: repo,
                labels: ['triage']
                });

                return comment.data.id;

        - run: |
            echo "Commented on issue with comment ID: ${{ steps.issue_comment.outputs.result }}"
          name: Print Comment ID