name: Thanks

on:
  issues:
    types: [opened]

  workflow_dispatch:

jobs:
    thanks:
        name: Thanks for opening an issue
        runs-on: ubuntu-latest
        permissions:
          issues: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
        - uses: actions/github-script@v9
          id: issue_comment
          with:
            script: |
                var issue_number = context.issue.number;
                console.log(`issue_number: ${issue_number}`);
                console.log(`owner: ${context.repo.owner}`);
                console.log(`repo: ${context.repo.repo}`);

                const issue = await github.rest.issues.get({
                    repo, owner, issue_number
                });
                console.log(`issue: ${issue}`);


                var comment = await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `👋 Thanks for opening issue #${context.issue.number}!`
                });

                github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['triage']
                });

                return comment.data.id;

        - run: |
            echo "Commented on issue with comment ID: ${{ steps.issue_comment.outputs.result }}"
          name: Print Comment ID