name: upper capture

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/06-upper-capture.yml"
      - "upper/**"
  workflow_dispatch: # manual

jobs:
    build:
        name: Capture Upper Build
        strategy:
           matrix:
             os: [ ubuntu-latest, windows-latest, macos-latest ]
        runs-on: ${{ matrix.os }}
        defaults:
          run:
            working-directory: upper
        steps:
        - uses: actions/checkout@v6
          name: Checkout Repository
          
        - run: pwd
          name: Print Working Directory

        - uses: actions/setup-go@v6
          with:
            go-version: '1.23.12'
            cache-dependency-path: ./upper/go.sum
        
        - if: runner.os == 'Windows'
          run: dir
          name: List Files on Windows
        
        - if: runner.os == 'Linux' || runner.os == 'macOS'
          run: ls -al
          name: List Files on Linux or macOS Before Build

        - run: go build
          name: Build Upper
        
        - if: runner.os == 'Windows'
          run: dir
          name: List Files on Windows After Build

        - if: runner.os == 'Linux' || runner.os == 'macOS'
          run: ls -al
          name: List Files on Linux or macOS After Build

        - run: go test
          name: Test Upper

        - uses: actions/upload-artifact@v7
          name: Upload Upper Build Artifacts
          with:
            name: upper-build-${{ runner.os }}
            path: ./upper/upper*
        
        